---
- name: server entry
  hosts: debserver
  become: true

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  roles:
    - system_dependencies
    - k3s_setup
    - cluster_resources
